version: '3'
services:
  mysql-standalone:

    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=Abhijeet
      - MYSQL_DATABASE=BillingPortal
    ports:
      - "3316:3306"


  springboot-docker-container:
    image: springboot-docker-container
    ports:
      - "3038:3030"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/BillingPortal?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "Abhijeet"
    build:
      context: "./"
    depends_on:
      - mysql-standalone